steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/<your-project-id>/fastapi-app", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/<your-project-id>/fastapi-app"]

images:
  - "gcr.io/amara1-481702/fastapi-app"
